spring:
  application:
    name: hh
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hh}
    username: ${DB_USERNAME:hh}
    password: ${DB_PASSWORD:hh}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

logging:
  level:
    org.apache.coyote.http11.Http11Processor: WARN
    pyc.lopatuxin.hh: DEBUG

hh:
  resume-id: ${HH_RESUME_ID}
  browser:
    auth-state-path: auth.json
    headless: true
    delay-min-ms: 10000
    delay-max-ms: 45000
    max-per-day: 50